### ISSUE TITLE
Code Refactoring Checklist

### ISSUE THREAD

**Issue by RyanGrieb** [RyanGrieb/OpenCiv#57]
- [ ] Remove ```this.``` in instances when it's not needed
Better readability in my opinion

- [ ] Create universal JSON object in Server
We don't need to create a new JSON object every time we want to send a packet to the player

- [x] Replace ```println``` in server with proper logging

* Start working on [code smells](https://sonarcloud.io/project/issues?id=rhin123_OpenCiv&open=AX5GSsZlNVtMtOJ2ecxr&resolved=false&types=CODE_SMELL)
